# Site settings
title: Arkay's Blog
description: ''
# url: 'https://quanganh206.github.io'
# baseurl: '/'
google_analytics: 'UA-111256185-1'
disqus_shortname: 'quanganh206github'

author:
  name: 'Quang Anh (Arkay Lee)'
  email: quanganh@aiti.com
  twitter_username: QuangAnh_AiTi
  github_username:  quanganh206
  linkedin_username:  lequanganh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-github-metadata']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
