# Site settings
title: Arkay's Blog
description: 'Another Technical Blog - xMobe'
url: 'https://lequanganh.com'
# baseurl: '/'
google_analytics: 'UA-111256185-1'
disqus_shortname: 'quanganh206github'
products:
  - name: 'ionFullApp 9ecom WooCommerce v4'
    image: 'https://firebasestorage.googleapis.com/v0/b/xmobe2018.appspot.com/o/xmobe2019%2Fimages%2F279caeb5-0dd2-b080-abe9-cb37a14ea242_undefined%2F279caeb5-0dd2-b080-abe9-cb37a14ea242_undefined.png?alt=media&token=7dedcc57-d8c4-48cf-87ea-44360d0670d7'
    price: '$369'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-9ecom-woocommerce-v4'
  - name: 'ionFullApp Ecommerce 9ecom v4'
    image: 'https://firebasestorage.googleapis.com/v0/b/xmobe2018.appspot.com/o/xmobe2019%2Fimages%2F01513a39-d806-c712-d441-12c597634b02_ionfullapp-ecommerce-9ecom-v4%2F01513a39-d806-c712-d441-12c597634b02_ionfullapp-ecommerce-9ecom-v4.png?alt=media&token=b298aa8d-1089-4402-b8f5-2555f66635e5'
    price: '$59'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-ecommerce-9ecom-v4'
  - name: 'ionFullApp Social 9 Food Recipe Edacious'
    image: 'https://xmobe.com/assets/images/2018/03/banner-new-1024.png?resize=768%2C576&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-social-9-food-recipe-edacious/'
  - name: 'ionFullApp Ecommerce App 9Beauty POSH'
    image: 'https://xmobe.com/assets/images/2018/03/banner-new-1024x768-01.png?resize=768%2C576&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-ecommerce-app-9beauty-posh/'
  - name: 'ionFullApp 9Bitcoin Crypto Currencies'
    image: 'https://xmobe.com/assets/images/2018/03/9bitcoin-sellfy01.png?resize=768%2C576&ssl=1'
    price: '$39'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-9bitcoin-crypto-currencies/'

  - name: 'ionFullApp Ecommerce App 9ecom'
    image: 'https://xmobe.com/assets/images/2018/03/9ecom.png?resize=768%2C576&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/shop/products/ionfull-ecommerce-app-9ecom/'
  - name: 'ionFullApp Social 9 Chat Group HeyU'
    image: 'https://xmobe.com/assets/images/2018/03/banner-new1024x768-01.png?zoom=2&fit=1024%2C768&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-social-9-chat-heyu/'
  - name: 'uShip Mobile – Heavy Transportation Open Market'
    image: 'https://xmobe.com/assets/images/2018/03/uShip-Sellfy2.png?resize=768%2C576&ssl=1'
    price: '$15,000'
    link: 'https://www.xmobe.com/shop/products/uship-mobile-heavy-transportation-open-market/'
  - name: 'Ionic2 Scrollable Tabs Component (Free)'
    image: 'https://xmobe.com/assets/images/2018/03/banner-new-1024x768-02-1.png?resize=768%2C576&ssl=1'
    price: 'Free'
    link: 'https://www.xmobe.com/shop/products/ionic2-scrollable-tabs-component-free/'
  - name: 'ionFullApp Social 9Chat HeyU – Firebase PRO'
    image: 'https://xmobe.com/assets/images/2018/03/banner-new1024x768-01-1.png?zoom=2&fit=1024%2C768&ssl=1'
    price: '$269'
    link: 'https://www.xmobe.com/shop/products/ionfullapp-social-9chat-heyu-firebase-pro/'
  - name: 'Ionic2 Calendar Component (Free)'
    image: 'https://xmobe.com/assets/images/2018/03/banner-new-1024-1.png?resize=768%2C576&ssl=1'
    price: 'Free'
    link: 'https://www.xmobe.com/shop/products/ionic2-calendar-component/'
  

author:
  name: 'Quang Anh (Arkay Lee)'
  email: quanganh@aiti.com
  twitter_username: QuangAnh_AiTi
  github_username:  quanganh206
  linkedin_username:  lequanganh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
future: false

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-github-metadata']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
