# Site settings
title: Arkay's Blog
description: 'Another Technical Blog'
# url: 'https://quanganh206.github.io'
# baseurl: '/'
google_analytics: 'UA-111256185-1'
disqus_shortname: 'quanganh206github'
products:
  - name: 'ionFullApp Social 9 Food Recipe Edacious'
    image: 'https://i1.wp.com/www.xmobe.com/wp-content/uploads/2018/03/banner-new-1024.png?resize=768%2C576&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/product/ionfullapp-social-9-food-recipe-edacious/'
  - name: 'ionFullApp Ecommerce App 9Beauty POSH'
    image: 'https://i1.wp.com/www.xmobe.com/wp-content/uploads/2018/03/banner-new-1024x768-01.png?resize=768%2C576&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/product/ionfullapp-ecommerce-app-9beauty-posh/'
  - name: 'ionFullApp 9Bitcoin Crypto Currencies'
    image: 'https://i0.wp.com/www.xmobe.com/wp-content/uploads/2018/03/9bitcoin-sellfy01.png?resize=768%2C576&ssl=1'
    price: '$39'
    link: 'https://www.xmobe.com/product/ionfullapp-9bitcoin-crypto-currencies/'

  - name: 'ionFullApp Ecommerce App 9ecom'
    image: 'https://i1.wp.com/www.xmobe.com/wp-content/uploads/2018/03/9ecom.png?resize=768%2C576&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/product/ionfull-ecommerce-app-9ecom/'
  - name: 'ionFullApp Social 9 Chat Group HeyU'
    image: 'https://i2.wp.com/www.xmobe.com/wp-content/uploads/2018/03/banner-new1024x768-01.png?zoom=2&fit=1024%2C768&ssl=1'
    price: '$29'
    link: 'https://www.xmobe.com/product/ionfullapp-social-9-chat-heyu/'
  - name: 'uShip Mobile – Heavy Transportation Open Market'
    image: 'https://i1.wp.com/www.xmobe.com/wp-content/uploads/2018/03/uShip-Sellfy2.png?resize=768%2C576&ssl=1'
    price: '$15,000'
    link: 'https://www.xmobe.com/product/uship-mobile-heavy-transportation-open-market/'
  - name: 'Ionic2 Scrollable Tabs Component (Free)'
    image: 'https://i0.wp.com/www.xmobe.com/wp-content/uploads/2018/03/banner-new-1024x768-02-1.png?resize=768%2C576&ssl=1'
    price: 'Free'
    link: 'https://www.xmobe.com/product/ionic2-scrollable-tabs-component-free/'
  - name: 'ionFullApp Social 9Chat HeyU – Firebase PRO'
    image: 'https://i0.wp.com/www.xmobe.com/wp-content/uploads/2018/03/banner-new1024x768-01-1.png?zoom=2&fit=1024%2C768&ssl=1'
    price: '$269'
    link: 'https://www.xmobe.com/product/ionfullapp-social-9chat-heyu-firebase-pro/'
  - name: 'Ionic2 Calendar Component (Free)'
    image: 'https://i1.wp.com/www.xmobe.com/wp-content/uploads/2018/03/banner-new-1024-1.png?resize=768%2C576&ssl=1'
    price: 'Free'
    link: 'https://www.xmobe.com/product/ionic2-calendar-component/'
  

author:
  name: 'Quang Anh (Arkay Lee)'
  email: quanganh@aiti.com
  twitter_username: QuangAnh_AiTi
  github_username:  quanganh206
  linkedin_username:  lequanganh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-github-metadata']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
